Add typedef
janis-commerce/router-fetcher pull request #11
Opened 2021-11-02 13:58 UTC by MarianoFndz

2021-11-02 23:03 UTC, gastonpereyra commented
⚠️ Falta la descripción del PR

2021-11-03 18:41 UTC, MarianoFndz commented
### Link al ticket
https://fizzmod.atlassian.net/browse/JCN-327

### Link a la subtarea
https://fizzmod.atlassian.net/browse/JCN-339

### Descripción del requerimiento
* Se requiere agreagar estos TypeDef al package de Microservice-Call
* Se requiere agregarlos también a Router-Fetcher que es un package que es fundamental al Ms-Call

### Descripción de la solución
Se realizo el requerimiento

2021-11-05 12:41 UTC, mdanelutti approved these changes

2021-11-05 13:25 UTC, gastonpereyra commented on lib/router-fetcher.js
> +	 * @return {RouterConfig}
NO :x: 

No retorna eso.. Recomiendo probarlo de verdad, por ejemplo agarrar un MS en local y fijarse que pasa..

2021-11-05 13:29 UTC, gastonpereyra commented on lib/router-fetcher.js
> +	 * @return {* | RouterFetcherError} The service schema
Porque `*` ?

 deberia devolver un Objeto, con el schema que se busca

2021-11-05 13:32 UTC, gastonpereyra commented on lib/router-fetcher.js
> +
Aprovechemos para mejorar  2 cosas que van quedando viejas:

1)

```js
- class RouterFetcher {
+ module.exports = class RouterFetcher   {
```

2) Cambiar la dependencia de `Request` que esta deprecada por `Axios`. Te parece ?

> Este cambió por ahi estaria bueno meterlo en el MicroserviceCall también

2021-11-09 17:19 UTC, gastonpereyra commented on package.json
>      "eslint": "^5.16.0",
```suggestion
    "eslint": "^7.31.0",
```

2021-11-10 17:51 UTC, gastonpereyra requested changes

2021-11-10 17:51 UTC, gastonpereyra commented on package.json
>      "request": "2.85.0"
ESta no va más

2021-11-10 17:51 UTC, gastonpereyra commented on lib/router-fetcher.js
> +	get axiosInstance() {
No crearia una instancia.. usaria Axios de una.. 

Por ejemplo para el endpoint

```js
const response = await axios.request({
  url: this.endpoint
  params
})
```

2021-11-10 17:51 UTC, gastonpereyra commented on lib/router-fetcher.js
> +	get axiosInstance() {
Si no le pasas `method` hace un `get` sino hay que pasarle `method: 'post'` (por ejemplo).

2021-11-10 17:51 UTC, gastonpereyra commented on lib/router-fetcher.js
> +const axios = require('axios');
Si agregamos esto, importamos los typeDef de Axios

```suggestion
const axios = require('axios').default;
```

2021-11-15 20:25 UTC, gastonpereyra commented on lib/router-fetcher.js
> +				validateStatus: () => true
No hace falta

2021-11-15 20:28 UTC, gastonpereyra commented on lib/router-fetcher.js
Habria que cambiar el `REQUEST_LIB_ERROR` por `AXIOS_LIB_ERROR`

2021-11-15 20:29 UTC, gastonpereyra commented on lib/router-fetcher.js
> +				responseType: 'json',
No hace falta, `json` es el default

2021-11-15 20:31 UTC, gastonpereyra requested changes
COmentarios minimos

2021-11-18 19:22 UTC, gastonpereyra approved these changes

2021-11-19 17:45 UTC, jormaechea approved these changes

2021-11-19 17:45 UTC, jormaechea commented on package.json
> +    "build-types": "tsc lib/router-fetcher.js --declaration --allowJs --emitDeclarationOnly --outDir types"
```suggestion
    "build-types": "tsc lib/router-fetcher.js --declaration --allowJs --emitDeclarationOnly --outDir types",
    "prepare": "husky install"
```

2021-11-19 17:50 UTC, merged